name: Pull Request Build

on:
  pull_request:
    branches:
      - develop   # Only trigger when PR targets 'develop'

jobs:
  build:
    name: PR Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # Or your Java version

      - name: Build with Maven
        run: mvn clean install --no-transfer-progress

      - name: Run Unit Tests
        run: mvn test
